import {
  CelebrationIcon,
  UrgentIcon,
  ThankYouIcon,
  CalmIcon,
  ProfessionalIcon,
  CreativeIcon,
  MotivationalIcon,
  SeasonalIcon,
} from "../components/MaterialIcons";

export const moods = {
  Celebration: {
    color: "bg-gradient-to-br from-yellow-200 to-orange-300",
    textColor: "text-orange-800",
    borderColor: "border-orange-300",
    icon: CelebrationIcon,
    description: "Perfect for birthdays, achievements, and happy announcements",
    ctaColor: "bg-orange-500 hover:bg-orange-600",
    accentColor: "text-orange-600",
  },
  Urgent: {
    color: "bg-gradient-to-br from-red-200 to-pink-300",
    textColor: "text-red-800",
    borderColor: "border-red-300",
    icon: UrgentIcon,
    description: "For time-sensitive updates and important alerts",
    ctaColor: "bg-red-500 hover:bg-red-600",
    accentColor: "text-red-600",
  },
  ThankYou: {
    color: "bg-gradient-to-br from-green-200 to-emerald-300",
    textColor: "text-green-800",
    borderColor: "border-green-300",
    icon: ThankYouIcon,
    description: "Express gratitude and appreciation to your audience",
    ctaColor: "bg-green-500 hover:bg-green-600",
    accentColor: "text-green-600",
  },
  Calm: {
    color: "bg-gradient-to-br from-blue-200 to-cyan-300",
    textColor: "text-blue-800",
    borderColor: "border-blue-300",
    icon: CalmIcon,
    description: "Peaceful and serene communications",
    ctaColor: "bg-blue-500 hover:bg-blue-600",
    accentColor: "text-blue-600",
  },
  Professional: {
    color: "bg-gradient-to-br from-gray-200 to-slate-300",
    textColor: "text-gray-800",
    borderColor: "border-gray-300",
    icon: ProfessionalIcon,
    description: "Business updates and formal communications",
    ctaColor: "bg-gray-600 hover:bg-gray-700",
    accentColor: "text-gray-600",
  },
  Creative: {
    color: "bg-gradient-to-br from-purple-200 to-pink-300",
    textColor: "text-purple-800",
    borderColor: "border-purple-300",
    icon: CreativeIcon,
    description: "Artistic and innovative content sharing",
    ctaColor: "bg-purple-500 hover:bg-purple-600",
    accentColor: "text-purple-600",
  },
  Motivational: {
    color: "bg-gradient-to-br from-indigo-200 to-purple-300",
    textColor: "text-indigo-800",
    borderColor: "border-indigo-300",
    icon: MotivationalIcon,
    description: "Inspire and motivate your audience",
    ctaColor: "bg-indigo-500 hover:bg-indigo-600",
    accentColor: "text-indigo-600",
  },
  Seasonal: {
    color: "bg-gradient-to-br from-amber-200 to-yellow-300",
    textColor: "text-amber-800",
    borderColor: "border-amber-300",
    icon: SeasonalIcon,
    description: "Holiday greetings and seasonal updates",
    ctaColor: "bg-amber-500 hover:bg-amber-600",
    accentColor: "text-amber-600",
  },
};
